/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package pl.olafgoj.bookstore.books.adapters.messagebroker.avro;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class BookMessage extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -7888514311344277829L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"BookMessage\",\"namespace\":\"pl.olafgoj.bookstore.books.adapters.messagebroker.avro\",\"fields\":[{\"name\":\"id\",\"type\":\"long\"},{\"name\":\"title\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"},\"avro.java.string\":\"String\"},{\"name\":\"writer\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"},\"avro.java.string\":\"String\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<BookMessage> ENCODER =
      new BinaryMessageEncoder<BookMessage>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<BookMessage> DECODER =
      new BinaryMessageDecoder<BookMessage>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<BookMessage> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<BookMessage> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<BookMessage> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<BookMessage>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this BookMessage to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a BookMessage from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a BookMessage instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static BookMessage fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public long id;
  @Deprecated public java.lang.String title;
  @Deprecated public java.lang.String writer;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public BookMessage() {}

  /**
   * All-args constructor.
   * @param id The new value for id
   * @param title The new value for title
   * @param writer The new value for writer
   */
  public BookMessage(java.lang.Long id, java.lang.String title, java.lang.String writer) {
    this.id = id;
    this.title = title;
    this.writer = writer;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return id;
    case 1: return title;
    case 2: return writer;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: id = (java.lang.Long)value$; break;
    case 1: title = value$ != null ? value$.toString() : null; break;
    case 2: writer = value$ != null ? value$.toString() : null; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'id' field.
   * @return The value of the 'id' field.
   */
  public long getId() {
    return id;
  }


  /**
   * Sets the value of the 'id' field.
   * @param value the value to set.
   */
  public void setId(long value) {
    this.id = value;
  }

  /**
   * Gets the value of the 'title' field.
   * @return The value of the 'title' field.
   */
  public java.lang.String getTitle() {
    return title;
  }


  /**
   * Sets the value of the 'title' field.
   * @param value the value to set.
   */
  public void setTitle(java.lang.String value) {
    this.title = value;
  }

  /**
   * Gets the value of the 'writer' field.
   * @return The value of the 'writer' field.
   */
  public java.lang.String getWriter() {
    return writer;
  }


  /**
   * Sets the value of the 'writer' field.
   * @param value the value to set.
   */
  public void setWriter(java.lang.String value) {
    this.writer = value;
  }

  /**
   * Creates a new BookMessage RecordBuilder.
   * @return A new BookMessage RecordBuilder
   */
  public static pl.olafgoj.bookstore.books.adapters.messagebroker.avro.BookMessage.Builder newBuilder() {
    return new pl.olafgoj.bookstore.books.adapters.messagebroker.avro.BookMessage.Builder();
  }

  /**
   * Creates a new BookMessage RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new BookMessage RecordBuilder
   */
  public static pl.olafgoj.bookstore.books.adapters.messagebroker.avro.BookMessage.Builder newBuilder(pl.olafgoj.bookstore.books.adapters.messagebroker.avro.BookMessage.Builder other) {
    if (other == null) {
      return new pl.olafgoj.bookstore.books.adapters.messagebroker.avro.BookMessage.Builder();
    } else {
      return new pl.olafgoj.bookstore.books.adapters.messagebroker.avro.BookMessage.Builder(other);
    }
  }

  /**
   * Creates a new BookMessage RecordBuilder by copying an existing BookMessage instance.
   * @param other The existing instance to copy.
   * @return A new BookMessage RecordBuilder
   */
  public static pl.olafgoj.bookstore.books.adapters.messagebroker.avro.BookMessage.Builder newBuilder(pl.olafgoj.bookstore.books.adapters.messagebroker.avro.BookMessage other) {
    if (other == null) {
      return new pl.olafgoj.bookstore.books.adapters.messagebroker.avro.BookMessage.Builder();
    } else {
      return new pl.olafgoj.bookstore.books.adapters.messagebroker.avro.BookMessage.Builder(other);
    }
  }

  /**
   * RecordBuilder for BookMessage instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<BookMessage>
    implements org.apache.avro.data.RecordBuilder<BookMessage> {

    private long id;
    private java.lang.String title;
    private java.lang.String writer;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(pl.olafgoj.bookstore.books.adapters.messagebroker.avro.BookMessage.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.title)) {
        this.title = data().deepCopy(fields()[1].schema(), other.title);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.writer)) {
        this.writer = data().deepCopy(fields()[2].schema(), other.writer);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
    }

    /**
     * Creates a Builder by copying an existing BookMessage instance
     * @param other The existing instance to copy.
     */
    private Builder(pl.olafgoj.bookstore.books.adapters.messagebroker.avro.BookMessage other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.title)) {
        this.title = data().deepCopy(fields()[1].schema(), other.title);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.writer)) {
        this.writer = data().deepCopy(fields()[2].schema(), other.writer);
        fieldSetFlags()[2] = true;
      }
    }

    /**
      * Gets the value of the 'id' field.
      * @return The value.
      */
    public long getId() {
      return id;
    }


    /**
      * Sets the value of the 'id' field.
      * @param value The value of 'id'.
      * @return This builder.
      */
    public pl.olafgoj.bookstore.books.adapters.messagebroker.avro.BookMessage.Builder setId(long value) {
      validate(fields()[0], value);
      this.id = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'id' field has been set.
      * @return True if the 'id' field has been set, false otherwise.
      */
    public boolean hasId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'id' field.
      * @return This builder.
      */
    public pl.olafgoj.bookstore.books.adapters.messagebroker.avro.BookMessage.Builder clearId() {
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'title' field.
      * @return The value.
      */
    public java.lang.String getTitle() {
      return title;
    }


    /**
      * Sets the value of the 'title' field.
      * @param value The value of 'title'.
      * @return This builder.
      */
    public pl.olafgoj.bookstore.books.adapters.messagebroker.avro.BookMessage.Builder setTitle(java.lang.String value) {
      validate(fields()[1], value);
      this.title = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'title' field has been set.
      * @return True if the 'title' field has been set, false otherwise.
      */
    public boolean hasTitle() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'title' field.
      * @return This builder.
      */
    public pl.olafgoj.bookstore.books.adapters.messagebroker.avro.BookMessage.Builder clearTitle() {
      title = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'writer' field.
      * @return The value.
      */
    public java.lang.String getWriter() {
      return writer;
    }


    /**
      * Sets the value of the 'writer' field.
      * @param value The value of 'writer'.
      * @return This builder.
      */
    public pl.olafgoj.bookstore.books.adapters.messagebroker.avro.BookMessage.Builder setWriter(java.lang.String value) {
      validate(fields()[2], value);
      this.writer = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'writer' field has been set.
      * @return True if the 'writer' field has been set, false otherwise.
      */
    public boolean hasWriter() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'writer' field.
      * @return This builder.
      */
    public pl.olafgoj.bookstore.books.adapters.messagebroker.avro.BookMessage.Builder clearWriter() {
      writer = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public BookMessage build() {
      try {
        BookMessage record = new BookMessage();
        record.id = fieldSetFlags()[0] ? this.id : (java.lang.Long) defaultValue(fields()[0]);
        record.title = fieldSetFlags()[1] ? this.title : (java.lang.String) defaultValue(fields()[1]);
        record.writer = fieldSetFlags()[2] ? this.writer : (java.lang.String) defaultValue(fields()[2]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<BookMessage>
    WRITER$ = (org.apache.avro.io.DatumWriter<BookMessage>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<BookMessage>
    READER$ = (org.apache.avro.io.DatumReader<BookMessage>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeLong(this.id);

    out.writeString(this.title);

    out.writeString(this.writer);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.id = in.readLong();

      this.title = in.readString();

      this.writer = in.readString();

    } else {
      for (int i = 0; i < 3; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.id = in.readLong();
          break;

        case 1:
          this.title = in.readString();
          break;

        case 2:
          this.writer = in.readString();
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










